export const weatherAcronymKeymap = {
    "FM": "From",
    "TEMPO": "Temporary",
    "BECMG": "Becoming",
    "PROB": "Probability",
    "FU": "Smoke",
    "VA": "Volcanic Ash",
    "HZ": "Haze",
    "DU": "Dust",
    "SA": "Sand",
    "BLDU": "Blowing dust",
    "BLSA": "Blowing sand",
    "PO": "Dust devil",
    "VCSS": "Vicinity sand storm",
    "BR": "Mist or light fog",
    "MIFG": "More or less continuous shallow fog",
    "VCTS": "Vicinity thunderstorm",
    "VIRGA": "Virga or precipitation not hitting ground",
    "VCSH": "Vicinity showers",
    "TS": "Thunderstorm with or without precipitation",
    "SQ": "Squalls",
    "FC": "Funnel cloud or tornado",
    "SS": "Sand or dust storm",
    "+SS": "Strong sand or dust storm",
    "BLSN": "Blowing snow",
    "DRSN": "Drifting snow",
    "VCFG": "Vicinity fog",
    "BCFG": "Patchy fog",
    "PRFG": "Fog, sky discernable",
    "FG": "Fog, sky undiscernable",
    "FZFG": "Freezing fog",
    "-DZ": "Light drizzle",
    "DZ": "Moderate drizzle",
    "+DZ": "Heavy drizzle",
    "-FZDZ": "Light freezing drizzle",
    "FZDZ": "Moderate freezing drizzle",
    "+FZDZ": "Heavy freezing drizzle",
    "-DZRA": "Light drizzle and rain",
    "DZRA": "Moderate to heavy drizzle and rain",
    "-RA": "Light rain",
    "RA": "Moderate rain",
    "+RA": "Heavy rain",
    "-FZRA": "Light freezing rain",
    "FZRA": "Moderate freezing rain",
    "+FZRA": "Heavy freezing rain",
    "-RASN": "Light rain and snow",
    "RASN": "Moderate rain and snow",
    "+RASN": "Heavy rain and snow",
    "-SN": "Light snow",
    "SN": "Moderate snow",
    "+SN": "Heavy snow",
    "SG": "Snow grains",
    "IC": "Ice crystals",
    "PE PL": "Ice pellets",
    "PE": "Ice pellets",
    "PL": "Ice pellets",
    "-SHRA": "Light rain showers",
    "SHRA": "Moderate rain showers",
    "+SHRA": "Heavy rain showers",
    "-SHRASN": "Light rain and snow showers",
    "SHRASN": "Moderate rain and snow showers",
    "+SHRASN": "Heavy rain and snow showers",
    "-SHSN": "Light snow showers",
    "SHSN": "Moderate snow showers",
    "+SHSN": "Heavy snow showers",
    "-GR": "Light showers with hail, not with thunder",
    "GR": "Moderate to heavy showers with hail, not with thunder",
    "TSRA": "Light to moderate thunderstorm with rain",
    "TSGR": "Light to moderate thunderstorm with hail",
    "+TSRA": "Thunderstorm with heavy rain",
    "UP": "Unknown precipitation",
    "NSW": "No significant weather"
};

export const skyAndConditionsKeymap = {
    "BKN": "Broken",
    "FM": "From",
    "TEMPO": "Temporary",
    "BECMG": "Becoming",
    "PROB": "Probability",
    "CB": "Cumulo-Nimbus",
    "IMC": "Instrument meteorological conditions",
    "IMPR": "Improving",
    "INC": "In Clouds",
    "INS": "Inches",
    "INTER": "Intermittent",
    "INTSF": "Intensify(ing)",
    "INTST": "Intensity",
    "JTST": "Jet stream",
    "KM": "Kilometers",
    "KMH": "Kilometers per hour",
    "KT": "Knots",
    "L": "Low pressure area",
    "LAN": "Land",
    "LDA": "Landing distance available",
    "LDG": "Landing",
    "LGT": "Light",
    "LOC": "Locally",
    "LSQ": "Line squall",
    "LSR": "Loose snow on runway",
    "LTG": "Lightning",
    "LYR": "Layer",
    "M": "Meters",
    "MAX": "Maximum",
    "MB": "Millibars",
    "MET": "Meteorological",
    "MI": "Shallow",
    "MIN": "Minutes",
    "MNM": "Minimum",
    "MOD": "Moderate",
    "MOV": "Move, moving",
    "MPS": "Meters per second",
    "MS": "Minus",
    "MSL": "Mean sea level",
    "MTW": "Mountain waves",
    "MU": "Runway friction coefficent",
    "NC": "No change",
    "NIL": "None, nothing",
    "NM": "Nautical mile(s)",
    "NMRS": "Numerous",
    "NO": "Not available",
    "NOSIG": "No significant change",
    "NS": "Nimbostratus",
    "NSC": "No significant clouds",
    "NSW": "No Significant Weather",
    "OBS": "Observation",
    "OBSC": "Obscuring",
    "OCNL": "Occasional",
    "OKTA": "Eight of sky cover",
    "OTP": "On top",
    "OTS": "Out of service",
    "OVC": "Overcast",
    "P": "Greater than highest reportable sensor value",
    "P6SM": "Visibility greater than 6 SM",
    "PAEW": "Personnel and equipment working",
    "PE": "Ice Pellets",
    "PJE": "Parachute Jumping Exercise",
    "PK WND": "Peak wind",
    "PLW": "Plow/plowed",
    "PNO": "Precipitation amount not available",
    "PO": "Dust/Sand Whirls",
    "PPR": "Prior permission required",
    "PR": "Partial",
    "PRESFR": "Pressure falling rapidly",
    "PRESRR": "Pressure rising rapidly",
    "PROB30": "Probability 30 percent",
    "PS": "Plus",
    "PSR": "Packed snow on runway",
    "PWINO": "Precipitation id sensor not available",
    "PY": "Spray",
    "R": "Runway (in RVR measurement)",
    "RA": "Rain",
    "RAB": "Rain Began",
    "RADAT": "Radiosonde observation addl data",
    "RAE": "Rain Ended",
    "RAPID": "Rapid(ly)",
    "RASN": "Rain and snow",
    "RCAG": "Remote Center Air/Ground Comm Facility",
    "RMK": "Remark",
    "RVR": "Runway visual range",
    "RVRNO": "RVR not available",
    "RY/RWY": "Runway",
    "SA": "Sand",
    "SAND": "Sandstorm",
    "SC": "Stratocumulus",
    "SCSL": "Stratocumulus standing lenticular cloud",
    "SCT": "Scattered cloud coverage",
    "SEC": "Seconds",
    "SEV": "Severe",
    "SFC": "Surface",
    "SG": "Snow Grains",
    "SH": "Shower",
    "SHWR": "Shower",
    "SIGMET": "Information from MWO",
    "SIR": "Snow and ice on runway",
    "SKC": "Sky Clear",
    "SLP": "Sea Level Pressure in MB",
    "SLPNO": "Sea-level pressure not available",
    "SLR": "Slush on runway",
    "SLW": "Slow",
    "SM": "Statute Miles",
    "SMK": "Smoke",
    "SMO": "Supplementary meteorological office",
    "SN": "Snow",
    "SPECI": "Special Report",
    "SQ": "Squall",
    "SS": "Sandstorm",
    "SSR": "Secondary Surveillance Radar",
    "T": "Temperature",
    "TAF": "Terminal aerodrome forecast in code",
    "TAPLEY": "Tapley runway friction coefficient",
    "TAR": "Terminal Area Surveillance Radar",
    "TAIL": "Tail wind",
    "TCH": "Threshold Crossing Height",
    "TCU": "Towering Cumulus",
    "TDO": "Tornado",
    "TDWR": "Terminal Doppler Weather Radar",
    "TEMPO": "TEMPO",
    "TEND": "Trend or tending to",
    "TKOF": "Takeoff",
    "TMPA": "Traffic Management Program Alert",
    "TODA": "Takeoff distance available",
    "TOP": "Cloud top",
    "TORA": "Takeoff run available",
    "TS": "Thunderstorm",
    "TSNO": "Thunderstorm/lightning detector not available",
    "TURB": "Turbulence",
    "TWY": "Taxiway",
    "UFN": "Until further notice",
    "UNL": "Unlimited",
    "UP": "Unknown Precipitation",
    "UTC": "Coordinated Universal Time (=GMT)",
    "V": "Variable (wind direction and RVR)",
    "VA": "Volcanic Ash",
    "VC": "Vicinity",
    "VER": "Vertical",
    "VFR": "Visual flight rules",
    "VGSI": "Visual Glide Slope Indicator",
    "VIS": "Visibility",
    "VISNO [LOC]": "Visibility Indicator at second location not available",
    "VMS": "Visual meteorological conditions",
    "VOLMET": "Meteorological information for aircraft in flight",
    "VRB": "Variable wind direction",
    "VRBL": "Variable",
    "VSP": "Vertical speed",
    "VV": "Vertical Visibility (indefinite ceiling)",
    "WAAS": "Wide Area Augmentation System",
    "WDSPR": "Widespread",
    "WEF": "With effect from",
    "WIE": "With immediate effect",
    "WIP": "Work in progress",
    "WKN": "Weaken(ing)",
    "WR": "Wet runway",
    "WS": "Wind shear",
    "WSHFT": "Wind shift (in minutes after the hour)",
    "WSP": "Weather Systems Processor",
    "WSR": "Wet snow on runway",
    "WST": "Convective Significant Meteorological Information",
    "WTSPT": "Waterspout",
    "WW": "Severe Weather Watch Bulletin",
    "WX": "Weather"
};